### ISSUE TITLE
Measure pilot sample

### ISSUE THREAD

**Issue by troettge** [troettge/Transparency-Ling#8]
Apply measures to pilot sample (four papers each)

- [x] Timo
- [x] Agatha @agboch 
- [x] Joseph @jvcasillas 
- [x] Liam @LiamKeeble 
- [x] Caitlin @caitlin91 
- [x] Kyle @mahowak 
- [x] Erin @doomlab 
- [x] Melanie @melroethlisberger

**Comment by troettge** [comment]
The list with randomly assigned papers is [HERE](https://github.com/troettge/Transparency-Ling/blob/main/data/pilot_list.txt)

**Comment by caitlin91** [comment]
@troettge where is the google form to do these? I can only find the pdf

**Comment by doomlab** [comment]
@caitlin91 https://forms.gle/VXe9VmZc4Giv5FNB6

**Comment by doomlab** [comment]
- My first article wasn't about language - shouldn't I be kicked out to the end when that happens?
- The second I couldn't access without requesting through interlibrary loan - how would we handle this normally? Just make a note?
- Here on 4.6 I'm not sure what to put (like should it be the middle one because it's no data AND OR no statement? 
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/27783894/119071505-eeb62400-b9b7-11eb-8168-d48a43ec5a39.png">
- Same thing here for 5.1: 
<img width="1205" alt="image" src="https://user-images.githubusercontent.com/27783894/119071628-291fc100-b9b8-11eb-8737-838186c19ac1.png">
(just notes to self for meeting!)
